### ISSUE TITLE
Install task is failing due to broken link

### ISSUE THREAD

**Issue by RaymondBaksh** [Oefenweb/ansible-slack#9]
This is the link that I can currently pull from the Slack site : 

https://downloads.slack-edge.com/desktop-releases/linux/x64/4.41.96/slack-desktop-4.41.96-amd64.deb

I believe the referenced slack version is not available anymore.

Please see attached picture.

![image](https://github.com/user-attachments/assets/e0d589e0-9d36-40bd-8a4a-29f19fc30a98)

**Comment by tersmitten** [comment]
Fixed in `v4.0.30`
